### ISSUE TITLE
Course Description (logged in and incomplete)

### ISSUE THREAD

**Issue by steffen74** [eduhub-org/eduhub#17]
If a user did not successfully complete a course. The enrollment status is incomplete. The shown site is then very similar to the site with "complete" status. However, the status messages are changed correspondingly, the section for the certificate download is not included and possible a different text is shown in the section on the tasks

### Details
- The format of the URL and the design can be taken from the site variant with "completed" status, except that the section for the certifocate download is excluded.
- The text of the status message should be "Du hast den Kurs leider nicht erfolgreich abgeschlossen."
- The text displayed in the section on the tasks now depends on whether a task was completed successfully (check corresponding field in the enrollment table). If a task was not completed successfully, it is changed to: "Du hast den zugehörigen Online-Kurs leider nicht erfolgreich abgeschlossen." or else "Du hast das Projekt “XYZ” leider nicht erfolgreich abgeschlossen."

### Optional and Future Implementations
- NA

**Comment by fschindler** [comment]
@steffen74 @ckru-cbb how does the data schema represents an incomplete course? Does `Enrollment.Status === ABORTED` mean incomplete?

**Comment by steffen74** [comment]
There is no differentiation between aborted and incomplete. So, yes `ABORTED `means incomplete as well.

**Comment by okwast** [comment]
> @steffen74 @ckru-cbb how does the data schema represents an incomplete course? Does `Enrollment.Status === ABORTED` mean incomplete?

See this conversation: https://bitglow-workspace.slack.com/archives/C020E25F7NV/p1628842027000900

**Comment by steffen74** [comment]
Felix already had the same question - should we maybe name it `INCOMPLETE` ?
