### ISSUE TITLE
Course Description (after or before application period)

### ISSUE THREAD

**Issue by steffen74** [eduhub-org/eduhub#19]
A user is reviewing the courses to check for which courses she/he might want to apply a soon as the application period starts or she/he reviews them after the application period to check what's currently given and what maybe might be interesting in the next semester.

### Details
- The design of the site is identical to the one for a user not being logged in (or logged in and not having applied to the course), however, the apply button is replaced by corresponding status messages:
  - If the current date is before the start of the application period, the following text is shown: "Bewerbungen sind ab dem [registration start] möglich!
  - If the current date is after the end of the application period, the following text is shown: "Bewerbungen sind erst wieder ab dem kommenden Semester möglich."

### Optional and Future Implementations
- NA

**Comment by fschindler** [comment]
@steffen74 @ckru-cbb should we use the fields `Program.ApplicationStart` and `Program.ApplicationEnd` for determining the application period?

What does the field `Course.BookingDeadline` is for?

**Comment by steffen74** [comment]
@fschindler The field `Program.ApplicationEnd` is used as default value for new courses. `Course.BookingDeadline` should rather be renamed `Course.ApplicationEnd`. Also, I wonder if it would be beneficial to to rename the corresponding program field to  `Program.DefaultApplicationEnd` to make clear that it is a default value, and in the same way for othr fields. What do you think? @fschindler 
The field `Program.ApplicationStart` is directly taken to determine the application start of the course.
