### ISSUE TITLE
Tasks for Course Description

### ISSUE THREAD

**Issue by okwast** [eduhub-org/eduhub#22]
Extends functionality of #15 

- A section on "Tasks" including:
  - A text indicating until when the task proof has to be uploaded (the date for the final upload is given in the Cours Default Values table) 
  - A dropdown menu to select a project from a given list of projects and an upload button for a selected project: These two elements are only shown if the field "projects" in the course table is TRUE; the list of projects for the drop down is given as well in the course table; if no project is selected, the upload button is deactivated.
  - A dropdown menu to select an online course task from a given list of tasks and an upload button for a selected project: These two elements are only shown if the field "online courses allowed" in the course table is TRUE; the list of online courses for the drop down is given as well in the course table; if no online course is selected, the upload button is deactivated.

**Comment by fschindler** [comment]
Hi @steffen74 @ckru-cbb we started a discussion about the type/format of the `Projects` and `OnlineCourses` column here: https://bitglow-workspace.slack.com/archives/C020E25F7NV/p1629723211005600

There is still no decision about this.

**Comment by steffen74** [comment]
@fschindler I think, we have to be a member of your Slack workspace to see the discussion. Do you want to copy it here maybe?

**Comment by steffen74** [comment]
Or is it in our common channel? Then just the link doesn't work.

**Comment by steffen74** [comment]
Her a more detailed description of the user story:
- The section Tasks is only displayed when `Course.CertificatePossible` is TRUE.
- The date until when the task has to be uploaded is given in `Program.PerformanceRecordDeadline`.
- The list of projects should be retrieved via the table `Project `by selecting the projects defined for the given course. However, currently the relationship from `Project `to `Course `is missing. Each project should be assigned to a course.
- For the list with online courses this should be pretty much equivalent, and there should be a table `onlineCourses `including the columns `id`, `title`, and `course`, which is currently missing.
@ckru-cbb Can you add those? Or do I get something wrong?
