### ISSUE TITLE
Integrate commercial identity providers for SSO

### ISSUE THREAD

**Issue by steffen74** [eduhub-org/eduhub#399]
Possible options are:

![Image](https://user-images.githubusercontent.com/24397546/225930972-782815af-a12e-4acb-8be3-677dd051c2a0.png)

**Comment by steffen74** [comment]
(GitHub,  LinkedIn)
Insta
Facebook
Google

**Comment by ericstumper** [comment]
Facebook isn't working because of a fb crawler and keycloak incompatibility. FB does not have any support to get this solved.
