### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by steffen74** [eduhub-org/eduhub#4]
This the standard footer, which is the same on all pages. Except spacing the footer is the same for desktop and mobile and generally static.

### Details
It is divided into 3 parts:
- The top part, with an image that should be shown at the top:
![grafik](https://user-images.githubusercontent.com/24397546/115138551-36e6cd00-a02d-11eb-9788-91f9693dd881.png)
- The center part, containing the links to three static pages:
![grafik](https://user-images.githubusercontent.com/24397546/115138678-dd32d280-a02d-11eb-86ed-383475083a97.png)
- The bottom part, with the copyright on the left and two circular dots on the right, which should become share icons in the future:
![grafik](https://user-images.githubusercontent.com/24397546/115138637-a5c42600-a02d-11eb-94d9-273924243a2e.png)

### Optional and Future Implementations
- In the future the footer might become dynamic markdown content, but for now it will be static. However, the URLs should be easily editable for non-developers, so keep them in a global config/constants file and document how to change them.

**Comment by okwast** [comment]
@steffen74 I added the icons for facebook and instagram now as I saw it in the designs.
![Screen Shot 2021-05-08 at 16 45 36](https://user-images.githubusercontent.com/13070135/117543372-d5f35900-b01c-11eb-81cc-c4e480195bdb.png)

Would you be able to provide the correct urls these should link to?

**Comment by steffen74** [comment]
> 
> 
> @steffen74 I added the icons for facebook and instagram now as I saw it in the designs.
> ![Screen Shot 2021-05-08 at 16 45 36](https://user-images.githubusercontent.com/13070135/117543372-d5f35900-b01c-11eb-81cc-c4e480195bdb.png)
> 
> Would you be able to provide the correct urls these should link to?

Sure! The links are the following:
Instagram: https://www.instagram.com/opencampus_sh/
Facebook: https://de-de.facebook.com/opencampus.sh/
Great that you are already taking care of it,
