### ISSUE TITLE
Backend Table Changes

### ISSUE THREAD

**Issue by steffen74** [eduhub-org/eduhub#49]
For the implementation of admin frontend some new, additional fields are needed.

### Details
**Table Program**
- Field Name: max_length=40
- New text field "ShortName"; max_length=6
- New integer field "MaxMissedSessions"; default=2
- 3 new text fields: "QuestionnaireStart", "QuestionnaireSpeaker", "QuestionnaireEnd" (for the links to the corresponding questionnaires)
- For the upload of the certificate templates in total 4 new fields are needed, 2 for the original names of the files and 2 for the link where they are stored on the server: "FileNameTemplateParticipationCertificate", "FileNameTemplatePerformanceCertificate", "FileLinkTemplateParticipationCertificate", "FileLinkTemplatePerformanceCertificate"
- 2 new boolean fields to set the visibility of the certificates: "VisiblityParticipationCertificate", "VisibilityPerformanceCertificate"; default for both is FALSE.

**Table User**
- New text Field "UniversityOther" (for entering the name of a university not listed in the table University)

**Table Course**
- New boolean field "Visibility"; default=FALSE
- Change filed Status according to the description given below for the ENUM table
- BookingDeadline --> ApplicationEnd
- "DayOfTheWeek" --> "WeekDay"
- "TimeOfStart" --> "TimeStart"
- "Duration" --> "TimeEnd"
- Multiple Locations --> new join table
- MaxMissedDates --> MaxMissedSessions

**Instructor**
- Person --> User

**Table Location**
- A new table with possible values for the dropdown to select a location
- For the seed data, it should be "ONLINE" and "KIEL"
- LocationName --> Name verlinkt mit ENUM Table

**ENUM Table CourseStatus:**
The fields of the table should be the following:
- DRAFT
- READY_FOR_PUBLICATION
- READY_FOR_APPLICATION
- APPLICANTS_INVITED
- PARTICIPANTS_RATED
For migration all past courses withe status "FINISHED" should be set to "PARTICIPANTS_RATED, all courses marked as "ACTIVE" to "APPLICANTS_INVITED" and all other courses to "DRAFT"

**ENUM Table LocationOptions:**
The table includes only one value by default (which must not be deleted)
- ONLINE
For migration additionally "KIEL" is to be included

**CourseDefaultValues**
- "Semester" can be removed
- New text field Language; for migration set to "de"
- Default for MaxParticipants is an empty field (equals no restriction on number of participants) (positiver Integer oder leer)
- "Location": for migration set to "KIEL"

**Table Session**
- the field "Date" is missing
- Start --> TimeStart
- Finish --> TimeEnd
- Join Table für "Address" (not Location)
- "SessionReferents" --> "Speaker"
- Title --> Name (its named "Name in all other cases as well, should be her accordingly)

**ENUM Table MotivationGrade**
- Rename table to "MotivationRating"
- BAD --> DECLINE
- AVERAGE --> REVIEW
- GOOD --> INVITE

**Table Enrollment**
- MotivationGrade --> MotivationRating
- CertificateURL --> FileLinkPerformanceCertificate
- CertificateOfParticipationURL --> FileLinkParticipationCertificate
- New field "Performance - Rating"
- UploadFile --> FileLinkPerformanceRecord

**new ENUM Table PerformanceRating**
- "UNRATED"
- "PASSED"
- "FAILED"

**Table Attendence**
- Table name should be "Attendance" (and in the same way table "AttendanceDocument")
- Attending --> Status
- New field "Source" (ENUM Table AttendanceSource "ZOOM", "INSTRUCTOR" 

**new ENUM Table AttendanceStatus**
- "NO_INFO"
- "ATTENDED"
- "MISSED"

### Optional and Future Implementations
- NA

**Comment by ckru-kiel** [comment]
the field "Date" is missing
Start --> TimeStart
Finish --> TimeEnd
Currently Start and finish are datetimes so technically one session could last through a day change. For hypothetical events like a weeekend seminar or a special event overnight session like night of the profs or whatever.

**Comment by ckru-kiel** [comment]
Join Table für "Address" (not Location)
but an address table doesnt exist. what should it look like and how is it related to location?

**Comment by steffen74** [comment]
> 
> 
> the field "Date" is missing
> Start --> TimeStart
> Finish --> TimeEnd
> Currently Start and finish are datetimes so technically one session could last through a day change. For hypothetical events like a weeekend seminar or a special event overnight session like night of the profs or whatever.

You are right it should rather be re-named to `startDateTime ` and `endDatetime`.

**Comment by steffen74** [comment]
> 
> 
> Join Table für "Address" (not Location)
> but an address table doesnt exist. what should it look like and how is it related to location?

@ckru-cbb The former table `location` should be renamed to the table `address`. (I just noticed, there is a typo in the field `Longitude`.)
Also, the new table `location `can simply be an ENUM.
There is no technical relationship between the tables location and address.

**Comment by fschindler** [comment]
I've just finished my review on #75 and merged it.

@steffen74 @ckru-cbb should we close this issue?

**Comment by steffen74** [comment]
> 
> 
> I've just finished my review on #75 and merged it.
> 
> @steffen74 @ckru-cbb should we close this issue?

Sounds good!
