### ISSUE TITLE
Termine im Tab "Teilnahmen & Leistungen" anzeigen

### ISSUE THREAD

**Issue by ronjai** [eduhub-org/eduhub#597]
Link: https://edu.opencampus.sh/manage/course/340

<img width="1313" alt="Bildschirmfoto 2023-07-25 um 16 36 00" src="https://github.com/edu-hub-project/application/assets/89401844/414063f0-94ad-4eac-86b7-9a4403ca0492">

- NA

**Comment by ericstumper** [comment]
@ronjai I had already added them on hover. Should they still be displayed somewhere above the dots?

**Comment by ronjai** [comment]
@ericstumper No thanks, it works for me like this.
