### ISSUE TITLE
Bug: Upload of zipped project file

### ISSUE THREAD

**Issue by ronjai** [eduhub-org/eduhub#599]
- Hedda Bonatz
https://chat.opencampus.sh/opencampus/pl/5kqcjmou9tdwpx53371uok644o
The website seems to crash when we try to upload our zipped project file. Is there any other option to submit our project?

![image(1)](https://github.com/edu-hub-project/application/assets/89401844/0cfa208a-06f3-473d-8524-51a93ca8f60e)

Further error message:
- "Hey Ronja, irgendwie kann ich bei der EDU Plattform den Leistungsnachweis nicht hochladen. Da erscheint immer ein Fenster mit der Nachricht "operation-failed Load faules". Ich habe eine Beschreibung angegeben und auch die Autoren und die Dokumentation hinzugefügt, aber irgendwie kann ich das nicht hochladen - woran kann das liegen?"
- Freya Johannsen, User Experience Design
- https://edu.opencampus.sh/manage/course/326

**Comment by steffen74** [comment]
Will be completed by a different issue
