### ISSUE TITLE
Maximum number of participants in a course

### ISSUE THREAD

**Issue by steffen74** [eduhub-org/eduhub#632]
**Current problem**
It is possible to set the number of maximum participants for a course.
Currently the number is not used during the confirmation or acceptance process.

**Solution**
Remove the option to define the number of maximum participants for a course or apply it as needed.

**Comment by Tushar98644** [comment]
@steffen74 I would like to work on this under hacktoberfest

**Comment by steffen74** [comment]
@Tushar98644 Currently we do not apply the field. You are welcome to remove the field from the GUI of the corresponding manage course object. The field in the table should still be kept however.
