### ISSUE TITLE
Änderung des eingeblendeteten Textes unterhalb der Kursbeschreibung

### ISSUE THREAD

**Issue by ronjai** [eduhub-org/eduhub#672]
NEUER TEXT:

**Online-Teilnahme:**
Die Teilnahme an Terminen wird nur dann als anwesend gewertet, wenn die Kamera eingeschaltet ist.

**Kosten:**
Unsere Kurse sind offen für alle und kostenlos für Studierende, Schüler:innen, Auszubildende, Gründer:innen, Lehrkräfte, wissenschaftliche Mitarbeiter:innen, Arbeitssuchende, Geflüchtete und Rentner:innen. Für Berufstätige fällt eine Gebühr in Höhe von 200 Euro für den Erwerb eines Leistungszertifikats an. Der Erwerb eines Leistungszertifikats ist in verschiedenen Kursen mit kursinternen Projekten eine Teilnahmevoraussetzung. Über [team@opencampus.sh](mailto:team@opencampus.sh) kann ein Stipendium beantragt werden.

**Comment by steffen74** [comment]
@ronjai Ich hatte schon einen neuen Text eingefügt, hattest Du den schon gesehen?

**Comment by ronjai** [comment]
@steffen74 Ja, aber der müsste bitte nochmal geändert werden (siehe Slack) – DANKE!
