### ISSUE TITLE
Layout in some mobile versions

### ISSUE THREAD

**Issue by steffen74** [eduhub-org/eduhub#753]
Sometime the layout is too small:

![grafik](https://github.com/eduhub-org/eduhub/assets/24397546/58f5134d-e181-4a20-9a7c-df07ac562c8f)
![grafik](https://github.com/eduhub-org/eduhub/assets/24397546/85a62775-c40d-44c4-96c5-853575acd592)

iPhone SE, Softwareversion 15.7.9, Firefox

**Comment by Tushar98644** [comment]
@steffen74 I would like to take up this issue under hacktoberfest

**Comment by steffen74** [comment]
> @steffen74 I would like to take up this issue under hacktoberfest

@Tushar98644 You are very welcome to do it!
