### ISSUE TITLE
Up- and Download of Files in a Storage Bucket

### ISSUE THREAD

**Issue by freerafiki** [eduhub-org/eduhub#79]
Implementation of a serverless function to allow up- and download of a file.
The files are saved in a Google storage bucket and a Hasura update, insert, or select will be done with a header that allows to check who calls the function and if she(he has sufficient privileges. 

### Details
The files will be up- and downloaded according to the following structure and the reading and writing access is according to descriptions provided below:

**Fallback Images**
public/fallback_images/course_cover_image.png
read: public
write: admins only

** Logo images **
public/logos/<logo_name>
read: public
write: admins only

**User Profile Images**
public/<User.id>/profile_image/<upload_file_name>
read: public
write: user with the corresponding User.id and admins

**Cover Images for Courses**
public/<Course.id>/cover_image/<upload_file_name>
read: public
write: instructors for the corresponding course und admins

**Cover Images for Achievement Records**
public/<AchievementRecord.id>/cover_image/<upload_file_name>
read: public
write: user that are authors of the achievement record and admins

**Achievement Certificates**
<User.id>/<Course.id>/achievement_certificate_<Course.title>.pdf
read:  user with the corresponding anonymousId, instructors for the course withe the corresponding Course.Id, and admins
write: only admins

**Participation Certificates**
<anonymousId>/<Course.id>/participation_certificate_<Course.title>.pdf
read:  user with the corresponding anonymousId, instructors for the course withe the corresponding Course.Id, and admins
write: only admins

**Templates Achievement Certificate**
<program_id>/achievement_certificate_template/<uploaded_filename>
read/write: only admins

**Templates Participation Certificates**
<Program.id>/participation_certificate_template/<uploaded_filename>
read/write: only admins

### Optional and Future Implementations
- NA

**Comment by steffen74** [comment]
Possible Structure for the production and staging environment:

**production**
/attendance_certificates/
/achievement_certificates/
/project_records/<project_enrollment_id>
/profile_images/<uid>

**staging/development**
/test/...
/dev_<user>/...

**Comment by ckru-kiel** [comment]
I created two functions and uploaded them to branch feature/79-upload-file-via-hasura-to-a-storage-bucket

1. an Action(Mutation) to upload a file "saveFile". 
   The Action has two parameters 
   1. "base64file" which is a base 64 file blob 
   2. "filename" the filename which can be a full path
   The Action has a respons value "link" which is a link to the uploaded file which is accessible for 5 minutes
   Example:
  ```
  mutation saveFile {
    saveFile(base64file: "data:application/pdf;base64,JVBERi0xLjUKJcOkw7zDtsOfCjIgMCB...MGpVCwdiYWZtuglYNVFT0YK",  filename: "test/test.pdf")
  }
  ```
2. an Action(Query) to get a file link "loadFile".
  The Action has one parameter
  1. "filename"  the filename which can be a full path
  The Action has a respons value "link" which is a link to the uploaded file which is accessible for 5 minutes
  Example:
  ```
  query MyQuery {
     loadFile(path: "test/test.pdf") {
      link
    }
  }
  ```
The functions need two environment variables to work:
1. HASURA_CLOUD_FUNCTION_SECRET   the secret can be found in our google-cloud-secret-manager
2. HASURA_BUCKET  the bucket name to determine which bucket to upload to

I have not done much in way of a proper error management such as html responses if something goes wrong or security such as checking for allowed file types and sizes etc.

**Comment by ckru-kiel** [comment]
As of #209 this behavior has changed. There are now different actions for each file:

- loadAchievementCertificate : gets a SignedUrl from google to the achievementCertificate specified in the path parameter that is valid for 5 minutes. the fitting path parameter can be gotten from the achievementCertificateUrl field of the CourseEnrollment table.
- loadAchievementCertificateTemplate : gets a SignedUrl from google to the achievementCertificateTemplate specified in the path parameter that is valid for 5 minutes. the fitting path parameter can be gotten from the achievementCertificateTemplateUrl field of the Program table.
- loadParticipationCertificate : gets a SignedUrl from google to the participationCertificate specified in the path parameter that is valid for 5 minutes. the fitting path parameter can be gotten from the participationCertificateUrl field of the CourseEnrollment table.
- loadParticipationCertificateTemplate : gets a SignedUrl from google to the participationCertificateTemplate specified in the path parameter that is valid for 5 minutes. the fitting path parameter can be gotten from the participationCertificateTemplateUrl field of the Program table.
- saveAchievementCertificate : saves the given achievementCertificate (encoded as a base64 file) to the google bucket. The return value is a relative path that should be saved in the achievementCertificateUrl field in the CourseEnrollment table to be used with the loadAchievementCertificate action
- saveAchievementCertificateTemplate : saves the given achievementCertificateTemplate (encoded as a base64 file) to the google bucket. The return value is a relative path that should be saved in the achievementCertificateTemplateUrl field in the Program table to be used with the loadAchievementCertificateTemplate action
- saveAchievementRecordCoverImage : saves the given achievementRecordCoverImage (encoded as a base64 file) to the google bucket. The return value is a url to a public file in the google bucket and should be saved in the coverImageUrl field of the AchievementRecord table for future retrieval
- saveCourseImage : saves the given courseImage (encoded as a base64 file) to the google bucket. The return value is a url to a public file in the google bucket and should be saved in the coverImage field of the Course table for future retrieval
- saveParticipationCertificate : saves the given participationCertificate (encoded as a base64 file) to the google bucket. The return value is a relative path that should be saved in the participationCertificateUrl field in the CourseEnrollment table to be used with the loadParticipationCertificate action
- saveParticipationCertificateTemplate : saves the given participationCertificateTemplate (encoded as a base64 file) to the google bucket. The return value is a relative path that should be saved in the participationCertificateTemplateUrl field in the Program table to be used with the loadParticipationCertificateTemplate action
- saveUserProfileImage : saves the given userProfileImage (encoded as a base64 file) to the google bucket. The return value is a url to a public file in the google bucket and should be saved in the picture field of the User table for future retrieval

**Comment by ckru-kiel** [comment]
- saveAchievementRecordDocumentation : saves the given achievementRecordDocumentation (encoded as a base64 file) to the google bucket. The return value is a relative path that should be saved in the documentationUrl field in the AchievementRecord table to be used with the loadAchievementRecordDocumentation action
- loadAchievementRecordDocumentation : gets a SignedUrl from google to the achievementRecordDocumentation specified in the path parameter that is valid for 5 minutes. the fitting path parameter can be gotten from the documentationUrl field of the AchievementRecord table.
