### ISSUE TITLE
Creating Certificates with Python

### ISSUE THREAD

**Issue by Sina-CAU** [eduhub-org/eduhub#802]
Hauptissue: Erstellung eines PDF Zertifikats mit Python auf Basis einer Jpeg Datei, die in einem Google Cloud Bucket liegt. Das Zertifikat soll individuell anpassbar sein durch austauschbare Daten, wie Name oder Online/Präsenzkurs

Libraries: Welche Python Libraries würden sich für die Lösung diese Issues anbieten und warum?

Benötigte Funktionen:
- download/upload des Zertifikats in den Google Cloud Bucket
- GraphQL Query mit der die benötigten Daten aus der Relation CourseEnrollment geholt werden
- Zertifikat generieren/individualisieren
     -  Dateinamen generieren 
- main Funktion mit static Werten wie z. B. des Source Blob Names, aus der die Vorlage kommt

**Comment by steffen74** [comment]
https://github.com/opencampus-sh/elearning/blob/keycloak/app/views/home/academy/attendence_certificate_rest.html.erb
