### ISSUE TITLE
Individual pages "project" and "online-course"

### ISSUE THREAD

**Issue by steffen74** [eduhub-org/eduhub#98]
Currently the `AchievementOption` table includes the full info independent of being of the option being an online course or an achievement option.
The goal is to replace the `AchievementOption` table by corresponding tables `Project` and `OnlineCourse`. which have a corresponding relationship to the table `AchievementOptionCourse`.

*original idea (might need to be revised and extended for online courses)*: 
Users must not be logged in to see the single project view. However if a user is not logged in and wants to upload a documentation, the sign-in window opens, forcing them to log-in first.
Considering the download of the documentation any user is allowed to do that (open source approach).

For users who are enrolled for the shown project (i.e. user is logged in) and already uploaded a documentation before the view includes an additional section below the upload button, showing the file name of the last submitted project documentation, the authors and the date it was uploaded.

### Details
- All views are mobile first, the desktop views should follow as much as possible the design of the desktop view for a course.
- For achievement options of type `DOCUMENTATION_AND_CSV` the design is given [here](https://www.figma.com/file/TtucXsvBOfZE7NZKzTimrA/edu-Wireframe-%E2%80%93-WIP?node-id=3396%3A10045).
- For achievement options of type `DOCUMENTATION` for a logged in user with previous uploads, the design is given [here](https://www.figma.com/file/TtucXsvBOfZE7NZKzTimrA/edu-Wireframe-%E2%80%93-WIP?node-id=3396%3A9862).
- For achievement records of type `DOCUMENTATION` the design is given [here](https://www.figma.com/file/TtucXsvBOfZE7NZKzTimrA/edu-Wireframe-%E2%80%93-WIP?node-id=3396%3A9719).

### Optional and Future Implementations
- NA

**Comment by pct-cclausen** [comment]
- Where is this UI displayed? 
- Is there a login necessary to display this UI? The figma page shows "anmelden" in the top right, but upload/download buttons dont make sense without a login?

**Comment by steffen74** [comment]
- The UI is displayed after clicking on the corresponding project tile here[.](https://www.figma.com/file/TtucXsvBOfZE7NZKzTimrA/edu-Wireframe-%E2%80%93-WIP?node-id=3389%3A9486&t=cC5f2d8x9QzS8w7R-4)
- Sorry for being so unspecific about the login status and what's supposed to been shown. It seems that I didn't finish the description considering the enrolled users. I completed the above description now by more details.

**Comment by pct-fahmed** [comment]
Is it possible to provide some details about "For achievement records of type DOCUMENTATION the design is given"?? 

I have some confusion: 
 1. There is no field in "AchievementRecord" table to specify the record type.
 2. What is the functionality of the button "Herunterladen↓"
 3. What this button will download
 4. When this button will be visible ?

**Comment by steffen74** [comment]
The view for the achievement record refers to achievement options there were successfully completed.
1. The type of the achievement record is the one given via the referenced `AchievementRecord.achievementOptionId`.
2. The button "Herunterladen" allows to download the achievement record documentation.
3. The button will download the file provided under `AchievementRecord.documentationUrl`.
4. The button is visible when the `AchievementRecord.rating` equals `PASSED`; it is visible for logged-in as well as for not logged-in user.
