### ISSUE TITLE
Display of certicicates

### ISSUE THREAD

**Issue by ronjai** [eduhub-org/eduhub#993]
The display of certificates does not work if it has already been opened before.

<img width="1136" alt="Bildschirmfoto 2024-07-05 um 11 44 17" src="https://github.com/eduhub-org/eduhub/assets/89401844/f12a7693-8a65-4049-a156-711b7a4fd6bc">

**Comment by steffen74** [comment]
Another error report (see EduHub Issues channel on Mattermost):
Ich habe aktuell das Problem, dass mir der Button zum Download der Leistungszertifikate in einigen Kursen und beim Machine Learning Degree nicht angezeigt wird. Bei den Kursen vom Wintersemester 2022/2023 (Deep Learning und Application of Transformer Models) funktioniert noch alles wie es soll. Machine Learning with TensorFlow (SoSe 2022) sowie die Kurse ab Sommersemester 2023 sind bei mir davon betroffen.

**Comment by steffen74** [comment]
The problem reported last was different and was due to the fact that the check boxes to display the certificates was not checked for various programs.
